// <auto-generated />
using System;
using CarMarketplace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarMarketplace.Data.Migrations
{
    [DbContext(typeof(CarMarketplaceDbContext))]
    [Migration("20230725193352_RenamedEntitiesAndMore")]
    partial class RenamedEntitiesAndMore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CarMarketplace.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EngineId")
                        .HasColumnType("int");

                    b.Property<int>("EuroStandart")
                        .HasColumnType("int");

                    b.Property<Guid?>("LenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Odometer")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TechnicalSpecificationURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransmissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinNumber")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.HasIndex("EngineId");

                    b.HasIndex("LenderId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("ModelId");

                    b.HasIndex("SellerId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.CarManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(29)
                        .HasColumnType("nvarchar(29)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Huyndai"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nissan"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Peugeot"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Opel"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Chevrolet"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Jaguar"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Jeep"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Kia"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Subaru"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Volvo"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Citroën"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Dacia"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Land Rover"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Mazda"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Mini"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Seat"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Škoda"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Smart"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Suzuki"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Rolls-Royce"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Ferrari"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Lamborghini"
                        });
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(29)
                        .HasColumnType("nvarchar(29)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManufacturerName = "Audi",
                            ModelName = "80"
                        },
                        new
                        {
                            Id = 2,
                            ManufacturerName = "Audi",
                            ModelName = "90"
                        },
                        new
                        {
                            Id = 3,
                            ManufacturerName = "Audi",
                            ModelName = "100"
                        },
                        new
                        {
                            Id = 4,
                            ManufacturerName = "Audi",
                            ModelName = "A1"
                        },
                        new
                        {
                            Id = 5,
                            ManufacturerName = "Audi",
                            ModelName = "A3"
                        },
                        new
                        {
                            Id = 6,
                            ManufacturerName = "Audi",
                            ModelName = "A4"
                        },
                        new
                        {
                            Id = 7,
                            ManufacturerName = "Audi",
                            ModelName = "A5"
                        },
                        new
                        {
                            Id = 8,
                            ManufacturerName = "Audi",
                            ModelName = "A6"
                        },
                        new
                        {
                            Id = 9,
                            ManufacturerName = "Audi",
                            ModelName = "A8"
                        },
                        new
                        {
                            Id = 10,
                            ManufacturerName = "Audi",
                            ModelName = "Q2"
                        },
                        new
                        {
                            Id = 11,
                            ManufacturerName = "Audi",
                            ModelName = "Q3"
                        },
                        new
                        {
                            Id = 12,
                            ManufacturerName = "Audi",
                            ModelName = "Q5"
                        },
                        new
                        {
                            Id = 13,
                            ManufacturerName = "Audi",
                            ModelName = "Q7"
                        },
                        new
                        {
                            Id = 14,
                            ManufacturerName = "Audi",
                            ModelName = "Q8"
                        },
                        new
                        {
                            Id = 15,
                            ManufacturerName = "Audi",
                            ModelName = "TT"
                        },
                        new
                        {
                            Id = 16,
                            ManufacturerName = "Audi",
                            ModelName = "R8"
                        },
                        new
                        {
                            Id = 17,
                            ManufacturerName = "BMW",
                            ModelName = "1 Series"
                        },
                        new
                        {
                            Id = 18,
                            ManufacturerName = "BMW",
                            ModelName = "2 Series"
                        },
                        new
                        {
                            Id = 19,
                            ManufacturerName = "BMW",
                            ModelName = "3 Series"
                        },
                        new
                        {
                            Id = 20,
                            ManufacturerName = "BMW",
                            ModelName = "4 Series"
                        },
                        new
                        {
                            Id = 21,
                            ManufacturerName = "BMW",
                            ModelName = "5 Series"
                        },
                        new
                        {
                            Id = 22,
                            ManufacturerName = "BMW",
                            ModelName = "6 Series"
                        },
                        new
                        {
                            Id = 23,
                            ManufacturerName = "BMW",
                            ModelName = "7 Series"
                        },
                        new
                        {
                            Id = 24,
                            ManufacturerName = "BMW",
                            ModelName = "8 Series"
                        },
                        new
                        {
                            Id = 25,
                            ManufacturerName = "BMW",
                            ModelName = "X1"
                        },
                        new
                        {
                            Id = 26,
                            ManufacturerName = "BMW",
                            ModelName = "X2"
                        },
                        new
                        {
                            Id = 27,
                            ManufacturerName = "BMW",
                            ModelName = "X3"
                        },
                        new
                        {
                            Id = 28,
                            ManufacturerName = "BMW",
                            ModelName = "X4"
                        },
                        new
                        {
                            Id = 29,
                            ManufacturerName = "BMW",
                            ModelName = "X5"
                        },
                        new
                        {
                            Id = 30,
                            ManufacturerName = "BMW",
                            ModelName = "X6"
                        },
                        new
                        {
                            Id = 31,
                            ManufacturerName = "BMW",
                            ModelName = "X7"
                        },
                        new
                        {
                            Id = 32,
                            ManufacturerName = "BMW",
                            ModelName = "i3"
                        },
                        new
                        {
                            Id = 33,
                            ManufacturerName = "BMW",
                            ModelName = "i8"
                        },
                        new
                        {
                            Id = 34,
                            ManufacturerName = "BMW",
                            ModelName = "M1"
                        },
                        new
                        {
                            Id = 35,
                            ManufacturerName = "BMW",
                            ModelName = "M2"
                        },
                        new
                        {
                            Id = 36,
                            ManufacturerName = "BMW",
                            ModelName = "M3"
                        },
                        new
                        {
                            Id = 37,
                            ManufacturerName = "BMW",
                            ModelName = "M4"
                        },
                        new
                        {
                            Id = 38,
                            ManufacturerName = "BMW",
                            ModelName = "M5"
                        },
                        new
                        {
                            Id = 39,
                            ManufacturerName = "BMW",
                            ModelName = "M6"
                        },
                        new
                        {
                            Id = 40,
                            ManufacturerName = "BMW",
                            ModelName = "M8"
                        },
                        new
                        {
                            Id = 41,
                            ManufacturerName = "BMW",
                            ModelName = "Z1"
                        },
                        new
                        {
                            Id = 42,
                            ManufacturerName = "BMW",
                            ModelName = "Z3"
                        },
                        new
                        {
                            Id = 43,
                            ManufacturerName = "BMW",
                            ModelName = "Z4"
                        },
                        new
                        {
                            Id = 44,
                            ManufacturerName = "BMW",
                            ModelName = "Z8"
                        },
                        new
                        {
                            Id = 45,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "A"
                        },
                        new
                        {
                            Id = 46,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "B"
                        },
                        new
                        {
                            Id = 47,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "C"
                        },
                        new
                        {
                            Id = 48,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "CL"
                        },
                        new
                        {
                            Id = 49,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "CLA"
                        },
                        new
                        {
                            Id = 50,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "CLS"
                        },
                        new
                        {
                            Id = 51,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "CLK"
                        },
                        new
                        {
                            Id = 52,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "E"
                        },
                        new
                        {
                            Id = 53,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "G"
                        },
                        new
                        {
                            Id = 54,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "GLA"
                        },
                        new
                        {
                            Id = 55,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "GLB"
                        },
                        new
                        {
                            Id = 56,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "GLC"
                        },
                        new
                        {
                            Id = 57,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "GLE"
                        },
                        new
                        {
                            Id = 58,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "GLS"
                        },
                        new
                        {
                            Id = 59,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "S"
                        },
                        new
                        {
                            Id = 60,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "SL"
                        },
                        new
                        {
                            Id = 61,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "S"
                        },
                        new
                        {
                            Id = 62,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "GT"
                        },
                        new
                        {
                            Id = 63,
                            ManufacturerName = "Mercedes-Benz",
                            ModelName = "ML"
                        },
                        new
                        {
                            Id = 64,
                            ManufacturerName = "Honda",
                            ModelName = "Civic"
                        },
                        new
                        {
                            Id = 65,
                            ManufacturerName = "Honda",
                            ModelName = "Jazz"
                        },
                        new
                        {
                            Id = 66,
                            ManufacturerName = "Honda",
                            ModelName = "HR-V"
                        },
                        new
                        {
                            Id = 67,
                            ManufacturerName = "Honda",
                            ModelName = "CR-V"
                        },
                        new
                        {
                            Id = 68,
                            ManufacturerName = "Honda",
                            ModelName = "Accord"
                        },
                        new
                        {
                            Id = 69,
                            ManufacturerName = "Honda",
                            ModelName = "City"
                        },
                        new
                        {
                            Id = 70,
                            ManufacturerName = "Honda",
                            ModelName = "Insight"
                        },
                        new
                        {
                            Id = 71,
                            ManufacturerName = "Honda",
                            ModelName = "CR-Z"
                        },
                        new
                        {
                            Id = 72,
                            ManufacturerName = "Honda",
                            ModelName = "Legend"
                        },
                        new
                        {
                            Id = 73,
                            ManufacturerName = "Honda",
                            ModelName = "Odyssey"
                        },
                        new
                        {
                            Id = 74,
                            ManufacturerName = "Honda",
                            ModelName = "Integra"
                        },
                        new
                        {
                            Id = 75,
                            ManufacturerName = "Honda",
                            ModelName = "S2000"
                        },
                        new
                        {
                            Id = 76,
                            ManufacturerName = "Huyndai",
                            ModelName = "Accend"
                        },
                        new
                        {
                            Id = 77,
                            ManufacturerName = "Huyndai",
                            ModelName = "Coupe"
                        },
                        new
                        {
                            Id = 78,
                            ManufacturerName = "Huyndai",
                            ModelName = "Elantra"
                        },
                        new
                        {
                            Id = 79,
                            ManufacturerName = "Huyndai",
                            ModelName = "i10"
                        },
                        new
                        {
                            Id = 80,
                            ManufacturerName = "Huyndai",
                            ModelName = "i20"
                        },
                        new
                        {
                            Id = 81,
                            ManufacturerName = "Huyndai",
                            ModelName = "i30"
                        },
                        new
                        {
                            Id = 82,
                            ManufacturerName = "Huyndai",
                            ModelName = "i40"
                        },
                        new
                        {
                            Id = 83,
                            ManufacturerName = "Huyndai",
                            ModelName = "Tucson"
                        },
                        new
                        {
                            Id = 84,
                            ManufacturerName = "Huyndai",
                            ModelName = "Santa Fe"
                        },
                        new
                        {
                            Id = 85,
                            ManufacturerName = "Huyndai",
                            ModelName = "Ioniq"
                        },
                        new
                        {
                            Id = 86,
                            ManufacturerName = "Huyndai",
                            ModelName = "Veloster"
                        },
                        new
                        {
                            Id = 87,
                            ManufacturerName = "Huyndai",
                            ModelName = "ix20"
                        },
                        new
                        {
                            Id = 88,
                            ManufacturerName = "Huyndai",
                            ModelName = "ix35"
                        },
                        new
                        {
                            Id = 89,
                            ManufacturerName = "Ford",
                            ModelName = "Fiesta"
                        },
                        new
                        {
                            Id = 90,
                            ManufacturerName = "Ford",
                            ModelName = "Focus"
                        },
                        new
                        {
                            Id = 91,
                            ManufacturerName = "Ford",
                            ModelName = "Puma"
                        },
                        new
                        {
                            Id = 92,
                            ManufacturerName = "Ford",
                            ModelName = "Kuga"
                        },
                        new
                        {
                            Id = 93,
                            ManufacturerName = "Ford",
                            ModelName = "Mondeo"
                        },
                        new
                        {
                            Id = 94,
                            ManufacturerName = "Ford",
                            ModelName = "Mustang"
                        },
                        new
                        {
                            Id = 95,
                            ManufacturerName = "Ford",
                            ModelName = "C-MAX"
                        },
                        new
                        {
                            Id = 96,
                            ManufacturerName = "Ford",
                            ModelName = "Escort"
                        },
                        new
                        {
                            Id = 97,
                            ManufacturerName = "Nissan",
                            ModelName = "Micra"
                        },
                        new
                        {
                            Id = 98,
                            ManufacturerName = "Nissan",
                            ModelName = "Juke"
                        },
                        new
                        {
                            Id = 99,
                            ManufacturerName = "Nissan",
                            ModelName = "Qashqai"
                        },
                        new
                        {
                            Id = 100,
                            ManufacturerName = "Nissan",
                            ModelName = "X-Trail"
                        },
                        new
                        {
                            Id = 101,
                            ManufacturerName = "Nissan",
                            ModelName = "Leaf"
                        },
                        new
                        {
                            Id = 102,
                            ManufacturerName = "Nissan",
                            ModelName = "Murano"
                        },
                        new
                        {
                            Id = 103,
                            ManufacturerName = "Nissan",
                            ModelName = "GT-R"
                        },
                        new
                        {
                            Id = 104,
                            ManufacturerName = "Nissan",
                            ModelName = "200sx"
                        },
                        new
                        {
                            Id = 105,
                            ManufacturerName = "Nissan",
                            ModelName = "240z"
                        },
                        new
                        {
                            Id = 106,
                            ManufacturerName = "Nissan",
                            ModelName = "280z"
                        },
                        new
                        {
                            Id = 107,
                            ManufacturerName = "Nissan",
                            ModelName = "300 zx"
                        },
                        new
                        {
                            Id = 108,
                            ManufacturerName = "Nissan",
                            ModelName = "350z"
                        },
                        new
                        {
                            Id = 109,
                            ManufacturerName = "Nissan",
                            ModelName = "370Z"
                        },
                        new
                        {
                            Id = 110,
                            ManufacturerName = "Nissan",
                            ModelName = "Note"
                        },
                        new
                        {
                            Id = 111,
                            ManufacturerName = "Nissan",
                            ModelName = "Terrano"
                        },
                        new
                        {
                            Id = 112,
                            ManufacturerName = "Nissan",
                            ModelName = "Patrol"
                        },
                        new
                        {
                            Id = 113,
                            ManufacturerName = "Nissan",
                            ModelName = "Skyline"
                        },
                        new
                        {
                            Id = 114,
                            ManufacturerName = "Nissan",
                            ModelName = "Silvia"
                        },
                        new
                        {
                            Id = 115,
                            ManufacturerName = "Renault",
                            ModelName = "Clio"
                        },
                        new
                        {
                            Id = 116,
                            ManufacturerName = "Renault",
                            ModelName = "Captur"
                        },
                        new
                        {
                            Id = 117,
                            ManufacturerName = "Renault",
                            ModelName = "Megane"
                        },
                        new
                        {
                            Id = 118,
                            ManufacturerName = "Renault",
                            ModelName = "Scenic"
                        },
                        new
                        {
                            Id = 119,
                            ManufacturerName = "Renault",
                            ModelName = "Twingo"
                        },
                        new
                        {
                            Id = 120,
                            ManufacturerName = "Renault",
                            ModelName = "Zoe"
                        },
                        new
                        {
                            Id = 121,
                            ManufacturerName = "Renault",
                            ModelName = "Talisman"
                        },
                        new
                        {
                            Id = 122,
                            ManufacturerName = "Renault",
                            ModelName = "Kangoo"
                        },
                        new
                        {
                            Id = 123,
                            ManufacturerName = "Renault",
                            ModelName = "Espace"
                        },
                        new
                        {
                            Id = 124,
                            ManufacturerName = "Renault",
                            ModelName = "Laguna"
                        },
                        new
                        {
                            Id = 125,
                            ManufacturerName = "Peugeot",
                            ModelName = "1007"
                        },
                        new
                        {
                            Id = 126,
                            ManufacturerName = "Peugeot",
                            ModelName = "106"
                        },
                        new
                        {
                            Id = 127,
                            ManufacturerName = "Peugeot",
                            ModelName = "107"
                        },
                        new
                        {
                            Id = 128,
                            ManufacturerName = "Peugeot",
                            ModelName = "108"
                        },
                        new
                        {
                            Id = 129,
                            ManufacturerName = "Peugeot",
                            ModelName = "2008"
                        },
                        new
                        {
                            Id = 130,
                            ManufacturerName = "Peugeot",
                            ModelName = "206"
                        },
                        new
                        {
                            Id = 131,
                            ManufacturerName = "Peugeot",
                            ModelName = "207"
                        },
                        new
                        {
                            Id = 132,
                            ManufacturerName = "Peugeot",
                            ModelName = "208"
                        },
                        new
                        {
                            Id = 133,
                            ManufacturerName = "Peugeot",
                            ModelName = "3008"
                        },
                        new
                        {
                            Id = 134,
                            ManufacturerName = "Peugeot",
                            ModelName = "306"
                        },
                        new
                        {
                            Id = 135,
                            ManufacturerName = "Peugeot",
                            ModelName = "307"
                        },
                        new
                        {
                            Id = 136,
                            ManufacturerName = "Peugeot",
                            ModelName = "308"
                        },
                        new
                        {
                            Id = 137,
                            ManufacturerName = "Peugeot",
                            ModelName = "4007"
                        },
                        new
                        {
                            Id = 138,
                            ManufacturerName = "Peugeot",
                            ModelName = "4008"
                        },
                        new
                        {
                            Id = 139,
                            ManufacturerName = "Peugeot",
                            ModelName = "406"
                        },
                        new
                        {
                            Id = 140,
                            ManufacturerName = "Peugeot",
                            ModelName = "407"
                        },
                        new
                        {
                            Id = 141,
                            ManufacturerName = "Peugeot",
                            ModelName = "408"
                        },
                        new
                        {
                            Id = 142,
                            ManufacturerName = "Peugeot",
                            ModelName = "5008"
                        },
                        new
                        {
                            Id = 143,
                            ManufacturerName = "Peugeot",
                            ModelName = "508"
                        },
                        new
                        {
                            Id = 144,
                            ManufacturerName = "Peugeot",
                            ModelName = "Partner"
                        },
                        new
                        {
                            Id = 145,
                            ManufacturerName = "Fiat",
                            ModelName = "Punto"
                        },
                        new
                        {
                            Id = 146,
                            ManufacturerName = "Fiat",
                            ModelName = "Stilo"
                        },
                        new
                        {
                            Id = 147,
                            ManufacturerName = "Fiat",
                            ModelName = "500"
                        },
                        new
                        {
                            Id = 148,
                            ManufacturerName = "Fiat",
                            ModelName = "Panda"
                        },
                        new
                        {
                            Id = 149,
                            ManufacturerName = "Fiat",
                            ModelName = "Tipo"
                        },
                        new
                        {
                            Id = 150,
                            ManufacturerName = "Fiat",
                            ModelName = "500L"
                        },
                        new
                        {
                            Id = 151,
                            ManufacturerName = "Fiat",
                            ModelName = "Doblo"
                        },
                        new
                        {
                            Id = 152,
                            ManufacturerName = "Fiat",
                            ModelName = "Bravo"
                        },
                        new
                        {
                            Id = 153,
                            ManufacturerName = "Fiat",
                            ModelName = "Multipla"
                        },
                        new
                        {
                            Id = 154,
                            ManufacturerName = "Fiat",
                            ModelName = "Fiorino"
                        },
                        new
                        {
                            Id = 155,
                            ManufacturerName = "Opel",
                            ModelName = "Insignia"
                        },
                        new
                        {
                            Id = 156,
                            ManufacturerName = "Opel",
                            ModelName = "Astra"
                        },
                        new
                        {
                            Id = 157,
                            ManufacturerName = "Opel",
                            ModelName = "Corsa"
                        },
                        new
                        {
                            Id = 158,
                            ManufacturerName = "Opel",
                            ModelName = "Zafira"
                        },
                        new
                        {
                            Id = 159,
                            ManufacturerName = "Opel",
                            ModelName = "Mokka"
                        },
                        new
                        {
                            Id = 160,
                            ManufacturerName = "Opel",
                            ModelName = "Antara"
                        },
                        new
                        {
                            Id = 161,
                            ManufacturerName = "Opel",
                            ModelName = "GT"
                        },
                        new
                        {
                            Id = 162,
                            ManufacturerName = "Opel",
                            ModelName = "Meriva"
                        },
                        new
                        {
                            Id = 163,
                            ManufacturerName = "Opel",
                            ModelName = "Frontera"
                        },
                        new
                        {
                            Id = 164,
                            ManufacturerName = "Toyota",
                            ModelName = "Yaris"
                        },
                        new
                        {
                            Id = 165,
                            ManufacturerName = "Toyota",
                            ModelName = "Corolla"
                        },
                        new
                        {
                            Id = 166,
                            ManufacturerName = "Toyota",
                            ModelName = "Auris"
                        },
                        new
                        {
                            Id = 167,
                            ManufacturerName = "Toyota",
                            ModelName = "C-HR"
                        },
                        new
                        {
                            Id = 168,
                            ManufacturerName = "Toyota",
                            ModelName = "RAV4"
                        },
                        new
                        {
                            Id = 169,
                            ManufacturerName = "Toyota",
                            ModelName = "Land Cruiser"
                        },
                        new
                        {
                            Id = 170,
                            ManufacturerName = "Toyota",
                            ModelName = "Prius"
                        },
                        new
                        {
                            Id = 171,
                            ManufacturerName = "Toyota",
                            ModelName = "Camry"
                        },
                        new
                        {
                            Id = 172,
                            ManufacturerName = "Toyota",
                            ModelName = "Supra"
                        },
                        new
                        {
                            Id = 173,
                            ManufacturerName = "Toyota",
                            ModelName = "Avensis"
                        },
                        new
                        {
                            Id = 174,
                            ManufacturerName = "Toyota",
                            ModelName = "Verso"
                        },
                        new
                        {
                            Id = 175,
                            ManufacturerName = "Toyota",
                            ModelName = "Aygo"
                        },
                        new
                        {
                            Id = 176,
                            ManufacturerName = "Toyota",
                            ModelName = "GT86"
                        },
                        new
                        {
                            Id = 177,
                            ManufacturerName = "Toyota",
                            ModelName = "Hilux"
                        },
                        new
                        {
                            Id = 178,
                            ManufacturerName = "Toyota",
                            ModelName = "Carina"
                        },
                        new
                        {
                            Id = 179,
                            ManufacturerName = "Toyota",
                            ModelName = "Celica"
                        },
                        new
                        {
                            Id = 180,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Spark"
                        },
                        new
                        {
                            Id = 181,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Aveo"
                        },
                        new
                        {
                            Id = 182,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Cruze"
                        },
                        new
                        {
                            Id = 183,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Trax"
                        },
                        new
                        {
                            Id = 184,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Captiva"
                        },
                        new
                        {
                            Id = 185,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Orlando"
                        },
                        new
                        {
                            Id = 186,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Corvette"
                        },
                        new
                        {
                            Id = 187,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Camaro"
                        },
                        new
                        {
                            Id = 188,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Matiz"
                        },
                        new
                        {
                            Id = 189,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Tahoe"
                        },
                        new
                        {
                            Id = 190,
                            ManufacturerName = "Chevrolet",
                            ModelName = "Tacuma"
                        },
                        new
                        {
                            Id = 191,
                            ManufacturerName = "Jaguar",
                            ModelName = "XE"
                        },
                        new
                        {
                            Id = 192,
                            ManufacturerName = "Jaguar",
                            ModelName = "XF"
                        },
                        new
                        {
                            Id = 193,
                            ManufacturerName = "Jaguar",
                            ModelName = "XJ"
                        },
                        new
                        {
                            Id = 194,
                            ManufacturerName = "Jaguar",
                            ModelName = "F-Type"
                        },
                        new
                        {
                            Id = 195,
                            ManufacturerName = "Jaguar",
                            ModelName = "F-Pace"
                        },
                        new
                        {
                            Id = 196,
                            ManufacturerName = "Jaguar",
                            ModelName = "E-Pace"
                        },
                        new
                        {
                            Id = 197,
                            ManufacturerName = "Jaguar",
                            ModelName = "I-Pace"
                        },
                        new
                        {
                            Id = 198,
                            ManufacturerName = "Jaguar",
                            ModelName = "S-Type"
                        },
                        new
                        {
                            Id = 199,
                            ManufacturerName = "Jaguar",
                            ModelName = "X-Type"
                        },
                        new
                        {
                            Id = 200,
                            ManufacturerName = "Jaguar",
                            ModelName = "XJR"
                        },
                        new
                        {
                            Id = 201,
                            ManufacturerName = "Jeep",
                            ModelName = "Renegade"
                        },
                        new
                        {
                            Id = 202,
                            ManufacturerName = "Jeep",
                            ModelName = "Compass"
                        },
                        new
                        {
                            Id = 203,
                            ManufacturerName = "Jeep",
                            ModelName = "Cherokee"
                        },
                        new
                        {
                            Id = 204,
                            ManufacturerName = "Jeep",
                            ModelName = "Grand Cherokee"
                        },
                        new
                        {
                            Id = 205,
                            ManufacturerName = "Jeep",
                            ModelName = "Wrangler"
                        },
                        new
                        {
                            Id = 206,
                            ManufacturerName = "Jeep",
                            ModelName = "Gladiator"
                        },
                        new
                        {
                            Id = 207,
                            ManufacturerName = "Jeep",
                            ModelName = "Commander"
                        },
                        new
                        {
                            Id = 208,
                            ManufacturerName = "Jeep",
                            ModelName = "Patriot"
                        },
                        new
                        {
                            Id = 209,
                            ManufacturerName = "Jeep",
                            ModelName = "Grand Wagoneer"
                        },
                        new
                        {
                            Id = 210,
                            ManufacturerName = "Jeep",
                            ModelName = "Patriot"
                        },
                        new
                        {
                            Id = 211,
                            ManufacturerName = "Kia",
                            ModelName = "Picanto"
                        },
                        new
                        {
                            Id = 212,
                            ManufacturerName = "Kia",
                            ModelName = "Rio"
                        },
                        new
                        {
                            Id = 213,
                            ManufacturerName = "Kia",
                            ModelName = "Stonic"
                        },
                        new
                        {
                            Id = 214,
                            ManufacturerName = "Kia",
                            ModelName = "Soul"
                        },
                        new
                        {
                            Id = 215,
                            ManufacturerName = "Kia",
                            ModelName = "Ceed"
                        },
                        new
                        {
                            Id = 216,
                            ManufacturerName = "Kia",
                            ModelName = "Optima"
                        },
                        new
                        {
                            Id = 217,
                            ManufacturerName = "Kia",
                            ModelName = "Stinger"
                        },
                        new
                        {
                            Id = 218,
                            ManufacturerName = "Kia",
                            ModelName = "Seltos"
                        },
                        new
                        {
                            Id = 219,
                            ManufacturerName = "Kia",
                            ModelName = "Sportage"
                        },
                        new
                        {
                            Id = 220,
                            ManufacturerName = "Kia",
                            ModelName = "Sorento"
                        },
                        new
                        {
                            Id = 221,
                            ManufacturerName = "Kia",
                            ModelName = "Venga"
                        },
                        new
                        {
                            Id = 222,
                            ManufacturerName = "Lexus",
                            ModelName = "IS"
                        },
                        new
                        {
                            Id = 223,
                            ManufacturerName = "Lexus",
                            ModelName = "ES"
                        },
                        new
                        {
                            Id = 224,
                            ManufacturerName = "Lexus",
                            ModelName = "GS"
                        },
                        new
                        {
                            Id = 225,
                            ManufacturerName = "Lexus",
                            ModelName = "LS"
                        },
                        new
                        {
                            Id = 226,
                            ManufacturerName = "Lexus",
                            ModelName = "RX"
                        },
                        new
                        {
                            Id = 227,
                            ManufacturerName = "Lexus",
                            ModelName = "NX"
                        },
                        new
                        {
                            Id = 228,
                            ManufacturerName = "Lexus",
                            ModelName = "LC"
                        },
                        new
                        {
                            Id = 229,
                            ManufacturerName = "Porsche",
                            ModelName = "911"
                        },
                        new
                        {
                            Id = 230,
                            ManufacturerName = "Porsche",
                            ModelName = "718 Boxster"
                        },
                        new
                        {
                            Id = 231,
                            ManufacturerName = "Porsche",
                            ModelName = "718 Cayman"
                        },
                        new
                        {
                            Id = 232,
                            ManufacturerName = "Porsche",
                            ModelName = "Panamera"
                        },
                        new
                        {
                            Id = 233,
                            ManufacturerName = "Porsche",
                            ModelName = "Macan"
                        },
                        new
                        {
                            Id = 234,
                            ManufacturerName = "Porsche",
                            ModelName = "Cayenne"
                        },
                        new
                        {
                            Id = 235,
                            ManufacturerName = "Porsche",
                            ModelName = "Taycan"
                        },
                        new
                        {
                            Id = 236,
                            ManufacturerName = "Porsche",
                            ModelName = "959"
                        },
                        new
                        {
                            Id = 237,
                            ManufacturerName = "Porsche",
                            ModelName = "944"
                        },
                        new
                        {
                            Id = 238,
                            ManufacturerName = "Porsche",
                            ModelName = "911 GT2"
                        },
                        new
                        {
                            Id = 239,
                            ManufacturerName = "Porsche",
                            ModelName = "911 GT3"
                        },
                        new
                        {
                            Id = 240,
                            ManufacturerName = "Porsche",
                            ModelName = "911 Turbo"
                        },
                        new
                        {
                            Id = 241,
                            ManufacturerName = "Porsche",
                            ModelName = "911 Carrera 4S"
                        },
                        new
                        {
                            Id = 242,
                            ManufacturerName = "Subaru",
                            ModelName = "Impreza"
                        },
                        new
                        {
                            Id = 243,
                            ManufacturerName = "Subaru",
                            ModelName = "XV"
                        },
                        new
                        {
                            Id = 244,
                            ManufacturerName = "Subaru",
                            ModelName = "Forester"
                        },
                        new
                        {
                            Id = 245,
                            ManufacturerName = "Subaru",
                            ModelName = "Outback"
                        },
                        new
                        {
                            Id = 246,
                            ManufacturerName = "Subaru",
                            ModelName = "Legacy"
                        },
                        new
                        {
                            Id = 247,
                            ManufacturerName = "Subaru",
                            ModelName = "Levong"
                        },
                        new
                        {
                            Id = 248,
                            ManufacturerName = "Subaru",
                            ModelName = "WRX"
                        },
                        new
                        {
                            Id = 249,
                            ManufacturerName = "Subaru",
                            ModelName = "BRZ"
                        },
                        new
                        {
                            Id = 250,
                            ManufacturerName = "Subaru",
                            ModelName = "Ascent"
                        });
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Crossover"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Coupe"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Convertible"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wagon/Estate"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Minivan"
                        });
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            Name = "White"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gray"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Yellow"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Orange"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Purple"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pink"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bronze"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Navy"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Teal"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Burgundy"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Charcoal"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Cream"
                        });
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("CoolantCapacity")
                        .HasColumnType("float");

                    b.Property<int?>("Displacement")
                        .HasColumnType("int");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Horsepower")
                        .HasColumnType("int");

                    b.Property<double?>("OilCapacity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Lender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lenders");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.RentPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("PricePerDay")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("RentPosts");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.SalePost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("SalePosts");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Car", b =>
                {
                    b.HasOne("CarMarketplace.Data.Models.ApplicationUser", null)
                        .WithMany("CarsOnSale")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("CarMarketplace.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarMarketplace.Data.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarMarketplace.Data.Models.Engine", "Engine")
                        .WithMany()
                        .HasForeignKey("EngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarMarketplace.Data.Models.Lender", null)
                        .WithMany("RentalCars")
                        .HasForeignKey("LenderId");

                    b.HasOne("CarMarketplace.Data.Models.CarManufacturer", "Make")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CarMarketplace.Data.Models.CarModel", "Model")
                        .WithMany("Cars")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CarMarketplace.Data.Models.Seller", "Seller")
                        .WithMany("CarOnSale")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Engine");

                    b.Navigation("Make");

                    b.Navigation("Model");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Lender", b =>
                {
                    b.HasOne("CarMarketplace.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.RentPost", b =>
                {
                    b.HasOne("CarMarketplace.Data.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarMarketplace.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.SalePost", b =>
                {
                    b.HasOne("CarMarketplace.Data.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarMarketplace.Data.Models.Seller", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Seller", b =>
                {
                    b.HasOne("CarMarketplace.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CarMarketplace.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CarMarketplace.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarMarketplace.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CarMarketplace.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("CarsOnSale");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.CarManufacturer", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.CarModel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Lender", b =>
                {
                    b.Navigation("RentalCars");
                });

            modelBuilder.Entity("CarMarketplace.Data.Models.Seller", b =>
                {
                    b.Navigation("CarOnSale");
                });
#pragma warning restore 612, 618
        }
    }
}
